#!/bin/bash
# COMMAND_SCHEMAS
# Include this file at the end of ${HOME}/.bashrc or ${HOME}/.bash_profile
# and put your fun stuff here to sepecify the schema of a shell

function set_command_color() {
   # LS_COLOR Macros
   local END="\e[m"
   local GREEN="\e[0;32m"
   local RED="\e[0;31m"
   local MAGENTA="\e[0;35m"
   local BLUE="\e[0;34m"
   local YELLOW="\e[0;33m"
   local CYAN="\e[0;36m"
   local BROWN="\e[0;43m"
   local PURPLE="\e[0;45m"
   local GREEN_BOLD="\e[1;32m"
   local RED_BOLD="\e[1;31m"
   local MAGENTA_BOLD="\e[1;35m"
   local BLUE_BOLD="\e[1;34m"
   local YELLOW_BOLD="\e[1;33m"
   local CYAN_BOLD="\e[1;36m"
   local BROWN_BOLD="\e[1;43m"
   local PURPLE_BOLD="\e[1;45m"

   # \A: HH:MM, \t or \D{%H:%M:%S}: HH:MM:SS \h: hostname
   # terminal title
   #export PROMPT_COMMAND='echo -ne "${MAGENTA_BOLD}FUN $GREEN_BOLD$USER@$short_hostname$END"'
   #export PS1="\e[1;37m[\e[m\e[1;32m\u\e[m\e[1;33m@\e[m\e[1;35m\h\e[m \e[4m\e[m\e[1;37m]\e[m\e[1;36m\e[m\\$\n"
   export PS1="${MAGENTA_BOLD}FUN $GREEN_BOLD[\t]\u \W \$ $END"
}

set_command_color
